// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2cPvJHzwtgQhx2OvPZRMMC2srM2VfNhQ',
    appId: '1:417468427084:web:4955633694e288113dfde9',
    messagingSenderId: '417468427084',
    projectId: 'melky-firebase',
    authDomain: 'melky-firebase.firebaseapp.com',
    storageBucket: 'melky-firebase.firebasestorage.app',
    measurementId: 'G-ZGSGRG2TX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN9rp84gIRet6jdUEjjQTUqPxB3BWgIsw',
    appId: '1:417468427084:android:c9438e83dc6b47fd3dfde9',
    messagingSenderId: '417468427084',
    projectId: 'melky-firebase',
    storageBucket: 'melky-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvq4uLFAx3_279Mp4DZipkqesePKpVRds',
    appId: '1:417468427084:ios:7aac60ce4e41a81e3dfde9',
    messagingSenderId: '417468427084',
    projectId: 'melky-firebase',
    storageBucket: 'melky-firebase.firebasestorage.app',
    iosBundleId: 'com.example.firebaseMelky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvq4uLFAx3_279Mp4DZipkqesePKpVRds',
    appId: '1:417468427084:ios:7aac60ce4e41a81e3dfde9',
    messagingSenderId: '417468427084',
    projectId: 'melky-firebase',
    storageBucket: 'melky-firebase.firebasestorage.app',
    iosBundleId: 'com.example.firebaseMelky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2cPvJHzwtgQhx2OvPZRMMC2srM2VfNhQ',
    appId: '1:417468427084:web:7c700f59bfbc2ea23dfde9',
    messagingSenderId: '417468427084',
    projectId: 'melky-firebase',
    authDomain: 'melky-firebase.firebaseapp.com',
    storageBucket: 'melky-firebase.firebasestorage.app',
    measurementId: 'G-TNF1X6BD7M',
  );

}